config/routes.rb
Rails.application.routes.draw do
  resources :todo_apps
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_app.rb
class TodoApp < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todo_apps_controller.rb
class TodoAppsController < ApplicationController
  before_action :set_todo_app, only: [:show, :edit, :update, :destroy]

  # GET /todo_apps
  # GET /todo_apps.json
  def index
    @todo_apps = TodoApp.all
  end

  # GET /todo_apps/1
  # GET /todo_apps/1.json
  def show
  end

  # GET /todo_apps/new
  def new
    @todo_app = TodoApp.new
  end

  # GET /todo_apps/1/edit
  def edit
  end

  # POST /todo_apps
  # POST /todo_apps.json
  def create
    @todo_app = TodoApp.new(todo_app_params)

    respond_to do |format|
      if @todo_app.save
        format.html { redirect_to @todo_app, notice: 'Todo app was successfully created.' }
        format.json { render :show, status: :created, location: @todo_app }
      else
        format.html { render :new }
        format.json { render json: @todo_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_apps/1
  # PATCH/PUT /todo_apps/1.json
  def update
    respond_to do |format|
      if @todo_app.update(todo_app_params)
        format.html { redirect_to @todo_app, notice: 'Todo app was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_app }
      else
        format.html { render :edit }
        format.json { render json: @todo_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_apps/1
  # DELETE /todo_apps/1.json
  def destroy
    @todo_app.destroy
    respond_to do |format|
      format.html { redirect_to todo_apps_url, notice: 'Todo app was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_app
      @todo_app = TodoApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_app_params
      params.require(:todo_app).permit(:name, :url, :rating, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_apps_helper.rb
module TodoAppsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>SelfhelpWiki</title>
    <%= csrf_meta_tags %>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todo_apps/_form.html.erb
<%= form_for(todo_app) do |f| %>
  <% if todo_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_app.errors.count, "error") %> prohibited this todo_app from being saved:</h2>

      <ul>
      <% todo_app.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :url %>
    <%= f.text_field :url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :rating %>
    <%= f.text_field :rating, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :picture %>
    <%= f.text_field :picture, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_apps/edit.html.erb
<h1>Editing Todo App</h1>

<%= render 'form', todo_app: @todo_app %>

<%= link_to 'Show', @todo_app %> |
<%= link_to 'Back', todo_apps_path %>

app/views/todo_apps/index.html.erb
<div class="row">
  <div class="col-md-12">
  <p id="notice"><%= notice %></p>

  <h1>Todo Apps</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Url</th>
        <th>Rating</th>
        <th>Picture</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @todo_apps.each do |todo_app| %>
        <tr>
          <td><%= todo_app.name %></td>
          <td><%= todo_app.url %></td>
          <td><%= todo_app.rating %></td>
          <td><%= image_tag todo_app.picture, height:100 %></td>
          <td><%= link_to 'Show', todo_app, class: 'btn btn-default' %></td>
          <td><%= link_to 'Edit', edit_todo_app_path(todo_app), class: 'btn btn-default' %></td>
          <td><%= link_to 'Destroy', todo_app, class: 'btn btn-danger' , method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Todo App', new_todo_app_path, class: 'btn btn-default' %>
  </div>
</div>

app/views/todo_apps/new.html.erb
<h1>New Todo App</h1>

<%= render 'form', todo_app: @todo_app %>

<%= link_to 'Back', todo_apps_path %>

app/views/todo_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo_app.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @todo_app.url %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @todo_app.rating %>
</p>

<p>
  <strong>Picture:</strong>
  <%= @todo_app.picture %>
</p>

<%= link_to 'Edit', edit_todo_app_path(@todo_app) %> |
<%= link_to 'Back', todo_apps_path %>